/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.model.Model_Card;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import com.raven.model.VolEvent;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JLabel;
import com.raven.model.Model_Menu;




/**
 *
 * @author RAVEN
 */
public class eventLog extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public eventLog(String ev, String loc, int hours, String date) {
        event = ev;
        location = loc;
        this.hours = hours;
        this.date = date;
        initComponents();
              //Create the scroll pane and add the table to it
              spTable = new javax.swing.JScrollPane(table);
              spTable.setVerticalScrollBar(new ScrollBar());
              spTable.getVerticalScrollBar().setBackground(Color.WHITE);
              spTable.getViewport().setBackground(Color.WHITE);
              JPanel p = new JPanel();
              p.setBackground(Color.WHITE);
              spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
              
              // Set the layout and add the components
              setLayout(new java.awt.BorderLayout());
              add(spTable, java.awt.BorderLayout.WEST);
              //table.addItem(new Model_Menu("10", "Log Out", Model_Menu.MenuType.MENU));
              JLabel eventLabel = new JLabel("Event");
              JLabel locationLabel = new JLabel("Location");
              JLabel hoursLoggedLabel = new JLabel("Hours Logged");
              JLabel dateLabel = new JLabel("Date");
              JLabel statusLabel = new JLabel("Status");
      
              // Create information labels
              JLabel eventNameLabel = new JLabel("Dog Shelter");
              JLabel locationTextLabel = new JLabel("Pleasanton Dog Shelter");
              JLabel hoursLoggedTextLabel = new JLabel("3");
              JLabel dateTextLabel = new JLabel("25 Apr, 2020");
              JLabel statusTextLabel = new JLabel(StatusType.PENDING.toString());


      
              // Set label colors
              eventLabel.setForeground(Color.BLUE);
              locationLabel.setForeground(Color.BLUE);
              hoursLoggedLabel.setForeground(Color.BLUE);
              dateLabel.setForeground(Color.BLUE);
              statusLabel.setForeground(Color.BLUE);
      
              // Set layout and add components
              setLayout(new java.awt.GridLayout(6, 2, 5, 5));
              spTable.add(eventLabel);
              spTable.add(eventNameLabel);
              spTable.add(locationLabel);
              spTable.add(locationTextLabel);
              spTable.add(hoursLoggedLabel);
              spTable.add(hoursLoggedTextLabel);
              spTable.add(dateLabel);
              spTable.add(dateTextLabel);
              spTable.add(statusLabel);
              spTable.add(statusTextLabel);
              //spTable.add(new Model_Menu("10", "Log Out", Model_Menu.MenuType.MENU))
    }

    public void f1ddRow(String[] m){
        table.addRow(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JLayeredPane();
        card1 = new com.raven.component.Card();
        card2 = new com.raven.component.Card();
        card3 = new com.raven.component.Card();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();

        

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private com.raven.component.Card card1;
    private com.raven.component.Card card2;
    private com.raven.component.Card card3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane panel;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    private javax.swing.JTextField textField;
    private String event;
    private String location;
    private int hours;
    private String date;

    // End of variables declaration//GEN-END:variables
}
