/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.model.Model_Card;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import com.raven.model.VolEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import java.awt.font.*;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;





/**
 *
 * @author RAVEN
 */
public class Form_1 extends javax.swing.JPanel {

    private javax.swing.JTextField eventTextField;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextField hoursTextField;
    private javax.swing.JTextField dateTextField;
    private JLabel eventLabel;
    private JLabel locationLabel;
    private JLabel hoursLabel;
    private JLabel dateLabel;
    private javax.swing.JButton addButton;
    /**
     * Creates new form Form_1
     */
    public Form_1() {
        initComponents();
    }

    public void f1ddRow(String[] m){
        table.addRow(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        card1 = new com.raven.component.Card();
        card2 = new com.raven.component.Card();
        card3 = new com.raven.component.Card();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();

        setBackground(new java.awt.Color(242, 242, 242));
        numberLabel = new JLabel();
        numberLabel.setFont(new Font("SansSerif", Font.BOLD, 85));
        numberLabel.setForeground(Color.WHITE);
        numberLabel.setBounds(700, -120, 400, 400);
        JLabel hoursApprovedLabel = new JLabel("Hours Approved");
        hoursApprovedLabel.setFont(new Font("SansSerif", Font.PLAIN, 18));
        hoursApprovedLabel.setForeground(Color.WHITE);
        hoursApprovedLabel.setBounds(700, -50, 400, 400);


        card1.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/stock.png")), "Hour Goal: 100", "1/01/2024", "PVSA Award"));
        card1.setBounds(700, -150, 400, 400);
        card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/stock.png")), " ", " ", " "));
        card2.setBounds(700, 200, 500, 500);
        card2.setSize(900, 800);
        panel.setSize(1000, 1000);card2.setLocation(700, -150); 
        card2.setColor1(new java.awt.Color(245, 245, 245));
        card1.setColor1(new java.awt.Color(142, 142, 250));
        card1.setColor2(new java.awt.Color(123, 123, 245));
        card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/stock.png")), " ", "  ", "  "));
        card3.setColor1(new java.awt.Color(245, 245, 245));
        card3.setColor2(new java.awt.Color(245, 245, 245));




// Set the card colors


        //numberLabel.setSize(300,300 );
        add(numberLabel);
        add(hoursApprovedLabel);
        add(panel);

        eventTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        hoursTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        eventLabel = new JLabel("Event:");
        locationLabel = new JLabel("Location:");
        hoursLabel = new JLabel("Hours Logged:");
        dateLabel = new JLabel("Date:");

        eventTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));
        locationTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));
        hoursTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));
        dateTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));

        eventLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        locationLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        hoursLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        dateLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        


        table = new com.raven.swing.Table();
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Event", "Location", "Hours Logged", "Date"}
        ));
        
        // Create the scroll pane and add the table to it
        spTable = new javax.swing.JScrollPane(table);
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        //spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        
      // Set the layout and add the components
        setLayout(new java.awt.BorderLayout());
        add(spTable, java.awt.BorderLayout.WEST);
        table.addRow(new Object[]{"Beach Cleanup", "Ocean Beach", "5", "07/12/2021"});
        table.addRow(new Object[]{"Youth Mentoring", "Community Center", "2", "09/08/2022"});
        table.addRow(new Object[]{"Fundraising Gala", "Grand Ballroom", "6", "11/19/2023"});
        table.addRow(new Object[]{"Hospital Volunteer", "City General Hospital", "4", "03/02/2024"});
        table.addRow(new Object[]{"Senior Home Visits", "Golden Acres Senior Home", "3", "08/10/2024"});
        table.addRow(new Object[]{"Community Garden", "Green Thumb Park", "4", "05/05/2025"});
        table.addRow(new Object[]{"Reading Program", "Public Library", "2", "09/14/2025"});
        table.addRow(new Object[]{"Homeless Shelter", "Hope Haven Shelter", "5", "12/09/2026"});
        table.addRow(new Object[]{"Blood Drive", "Community Center", "3", "03/20/2027"});
        table.addRow(new Object[]{"Red Cross Fundraiser", "San Francisco", "5", "05/15/2023"});
        
        //Goal NUmber
        
        panel.add(card1);
        //panel.add(card2);
        //panel.add(card3);
        add(panel);

       
       
       
         // Adjust the bounds as needed
        int totalHours = 0; // Replace with your desired number

        for(int i = 0; i<table.getColumnCount(); i++){
            totalHours+=Integer.valueOf(table.getValueAt(i, 2).toString());
        }

        numberLabel.setText(Integer.toString(totalHours));


        eventTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        hoursTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        eventLabel = new JLabel("Event:");
        locationLabel = new JLabel("Location:");
        hoursLabel = new JLabel("Hours Logged:");
        dateLabel = new JLabel("Date:");

        eventTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));
        locationTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));
        hoursTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));
        dateTextField.setFont(new Font("SansSerif", Font.PLAIN, 12));

        eventLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        locationLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        hoursLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        dateLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));

        // Create a JPanel to hold the text fields and labels
        // JPanel inputPanel = new JPanel();
        // inputPanel.setLayout(new java.awt.GridLayout(4, 2, 10, 10));
        // inputPanel.setBackground(Color.WHITE);

        // Add the labels and text fields to the input panel
        JPanel fields = new JPanel(new java.awt.GridLayout(8, 1));

        fields.add(eventLabel);
        fields.add(eventTextField);
        fields.add(locationLabel);
        fields.add(locationTextField);
        fields.add(hoursLabel);
        fields.add(hoursTextField);
        fields.add(dateLabel);
        fields.add(dateTextField);
        eventTextField.setFont(new Font("SansSerif", Font.PLAIN, 36));
        eventTextField.setPreferredSize(new Dimension(200, 36));
        locationTextField.setFont(new Font("SansSerif", Font.PLAIN, 36));
        locationTextField.setPreferredSize(new Dimension(200, 30));
        hoursTextField.setFont(new Font("SansSerif", Font.PLAIN, 36));
        hoursTextField.setPreferredSize(new Dimension(200, 30));
        dateTextField.setFont(new Font("SansSerif", Font.PLAIN, 36));
        dateTextField.setPreferredSize(new Dimension(200, 30));
        panel.add(fields);

// Add some spacing between the card and the text fields


        // Add the input panel to the main panel
       // add(inputPanel, java.awt.BorderLayout.NORTH);


        // JPanel buttonPanel = new JPanel();
        // buttonPanel.setBackground(Color.WHITE);

        // // Add the button to the button panel
        // addButton = new javax.swing.JButton("Add");
        // addButton.addActionListener(new ActionListener() {
        //     public void actionPerformed(ActionEvent e) {
        //         addEventData();
        //     }
        // });
        // buttonPanel.add(addButton);

        // // Add the button panel to the main panel
        // add(buttonPanel, java.awt.BorderLayout.SOUTH);







    }// </editor-fold>//GEN-END:initComponents

     private void addEventData() {
        String event = eventTextField.getText();
        String location = locationTextField.getText();
        String hours = hoursTextField.getText();
        String date = dateTextField.getText();

        // Add the event data to the table
        table.addRow(new Object[]{event, location, hours, date});

        // Clear the text fields
        eventTextField.setText("");
        locationTextField.setText("");
        hoursTextField.setText("");
        dateTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private com.raven.component.Card card1;
    private com.raven.component.Card card2;
    private com.raven.component.Card card3;
    private javax.swing.JLabel jLabel1;
    private JPanel panel;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    private javax.swing.JTextField textField;
    private JLabel numberLabel;



    // End of variables declaration//GEN-END:variables
}
